/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pagina;

import back_end.Classes.Usuario;
import back_end.Excepciones.PersistenciaException;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Registrarse extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    public Registrarse() {
        this.setContentPane(fondo);
        initComponents();
        setSize(1201, 718);
        setLocationRelativeTo(null); // Centrar ventana
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuadro_informacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        crear_cuenta = new javax.swing.JButton();
        cree_contraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confirmar_contraseña = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        correo_ = new javax.swing.JTextField();
        uid = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        semestre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        carrera1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cuadro_informacion.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Crear cuenta");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Correo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Cree una contraseña:");

        crear_cuenta.setBackground(new java.awt.Color(0, 0, 0));
        crear_cuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        crear_cuenta.setForeground(new java.awt.Color(255, 255, 255));
        crear_cuenta.setText("Crear cuenta");
        crear_cuenta.setToolTipText("");
        crear_cuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crear_cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crear_cuentaMouseClicked(evt);
            }
        });
        crear_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_cuentaActionPerformed(evt);
            }
        });

        cree_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cree_contraseñaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Confirmar contraseña:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setText("Escriba su nombre:");

        confirmar_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_contraseñaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setText("Carrera:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setText("Escriba su apellido:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel9.setText("Semestre que cursa:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel10.setText("ID:");

        javax.swing.GroupLayout cuadro_informacionLayout = new javax.swing.GroupLayout(cuadro_informacion);
        cuadro_informacion.setLayout(cuadro_informacionLayout);
        cuadro_informacionLayout.setHorizontalGroup(
            cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadro_informacionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(47, 47, 47)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cree_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmar_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo_, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carrera1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuadro_informacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crear_cuenta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(179, 179, 179))
        );
        cuadro_informacionLayout.setVerticalGroup(
            cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadro_informacionLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(correo_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cree_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmar_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(carrera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuadro_informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(crear_cuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/apuestas-online.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(cuadro_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cuadro_informacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void registrarUsuario() {
        try {
            // Obtener y validar datos del formulario
            String correoTexto = correo_.getText().trim();
            String contraseña = new String(cree_contraseña.getPassword());
            String confirmarContraseña = new String(confirmar_contraseña.getPassword());
            String nombreTexto = nombre.getText().trim();
            String apellidoTexto = apellido.getText().trim();
            String carreraTexto = carrera1.getText().trim();
            String uidTexto = uid.getText().trim();
            String semestreTexto = semestre.getText().trim();

            // Validación de campos vacíos
            if (!validarCamposVacios(correoTexto, contraseña, confirmarContraseña, 
                                   nombreTexto, apellidoTexto, carreraTexto, uidTexto, semestreTexto)) {
                return;
            }

            // Validar confirmación de contraseña
            if (!validarConfirmacionContraseña(contraseña, confirmarContraseña)) {
                return;
            }

            // Validar y convertir semestre
            int semestreInt = validarSemestre(semestreTexto);
            if (semestreInt == -1) {
                return;
            }

            // Crear y registrar usuario
            crearUsuario(uidTexto, nombreTexto, apellidoTexto, correoTexto, contraseña, carreraTexto, semestreInt);

        } catch (Exception e) {
            mostrarError("Error inesperado: " + e.getMessage());
            e.printStackTrace(); // Para debugging
        }
    }
    
    private boolean validarCamposVacios(String... campos) {
        for (String campo : campos) {
            if (campo == null || campo.isEmpty()) {
                mostrarAdvertencia("Por favor, complete todos los campos obligatorios.");
                return false;
            }
        }
        return true;
    }
    
    private boolean validarConfirmacionContraseña(String contraseña, String confirmarContraseña) {
        if (!contraseña.equals(confirmarContraseña)) {
            mostrarError("Las contraseñas no coinciden. Por favor, verifique e intente nuevamente.");
            // Limpiar campos de contraseña
            cree_contraseña.setText("");
            confirmar_contraseña.setText("");
            cree_contraseña.requestFocus();
            return false;
        }
        return true;
    }
    
    private int validarSemestre(String semestreTexto) {
        try {
            int semestreInt = Integer.parseInt(semestreTexto);
            if (semestreInt < 1 || semestreInt > 10) {
                mostrarAdvertencia("El semestre debe estar entre 1 y 10.");
                semestre.requestFocus();
                return -1;
            }
            return semestreInt;
        } catch (NumberFormatException e) {
            mostrarAdvertencia("Por favor, ingrese un número válido para el semestre.");
            semestre.requestFocus();
            return -1;
        }
    }
    
    private void crearUsuario(String uidTexto, String nombreTexto, String apellidoTexto, 
                             String correoTexto, String contraseña, String carreraTexto, int semestreInt) {
        try {
            // Crear instancia del usuario
            Usuario nuevoUsuario = new Usuario(uidTexto, nombreTexto, apellidoTexto, 
                                             correoTexto, contraseña, carreraTexto, semestreInt);

            // Intentar registrar el usuario (esto ejecuta todas las validaciones del backend)
            boolean registroExitoso = nuevoUsuario.registrarse(nombreTexto, apellidoTexto, 
                                                              correoTexto, contraseña, carreraTexto, semestreInt);

            if (registroExitoso) {
                mostrarExito();
            } else {
                mostrarError("No se pudo completar el registro. Intente nuevamente.");
            }

        } catch (IllegalArgumentException e) {
            // Errores de validación específicos del backend
            mostrarAdvertencia(e.getMessage());
            enfocarCampoSegunError(e.getMessage());
        } catch (PersistenciaException e) {
            // Errores de persistencia de datos
            mostrarError("Error al guardar los datos: " + e.getMessage());
        } catch (Exception e) {
            // Otros errores no previstos
            mostrarError("Error del sistema: " + e.getMessage());
        }
    }
    
    private void enfocarCampoSegunError(String mensajeError) {
        String mensaje = mensajeError.toLowerCase();
        
        if (mensaje.contains("correo")) {
            correo_.requestFocus();
        } else if (mensaje.contains("contraseña")) {
            cree_contraseña.requestFocus();
        } else if (mensaje.contains("nombre")) {
            nombre.requestFocus();
        } else if (mensaje.contains("apellido")) {
            apellido.requestFocus();
        } else if (mensaje.contains("carrera")) {
            carrera1.requestFocus();
        } else if (mensaje.contains("semestre")) {
            semestre.requestFocus();
        } else if (mensaje.contains("id universitario") || mensaje.contains("uid")) {
            uid.requestFocus();
        }
    }
    
    private void mostrarExito() {
        JOptionPane.showMessageDialog(this, 
                "¡Cuenta creada exitosamente!\n\n" +
                "Ya puede iniciar sesión con sus credenciales.", 
                "Registro Exitoso", 
                JOptionPane.INFORMATION_MESSAGE);
        
        // Limpiar formulario
        limpiarFormulario();
        
        // Redirigir al login después de un breve delay
        javax.swing.Timer timer = new javax.swing.Timer(1500, e -> {
            try {
                Login_1 ventanaLogin = new Login_1();
                ventanaLogin.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                mostrarError("Error al cargar la ventana de login: " + ex.getMessage());
            }
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    private void limpiarFormulario() {
        correo_.setText("");
        cree_contraseña.setText("");
        confirmar_contraseña.setText("");
        nombre.setText("");
        apellido.setText("");
        carrera1.setText("");
        uid.setText("");
        semestre.setText("");
    }
    
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void mostrarAdvertencia(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    
    private void cree_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cree_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cree_contraseñaActionPerformed

    private void crear_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_cuentaActionPerformed
        registrarUsuario();
    }//GEN-LAST:event_crear_cuentaActionPerformed

    private void crear_cuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crear_cuentaMouseClicked
        
    }//GEN-LAST:event_crear_cuentaMouseClicked

    private void confirmar_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmar_contraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField carrera1;
    private javax.swing.JPasswordField confirmar_contraseña;
    private javax.swing.JTextField correo_;
    private javax.swing.JButton crear_cuenta;
    private javax.swing.JPasswordField cree_contraseña;
    private javax.swing.JPanel cuadro_informacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField semestre;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {
        private Image imagen;

        @Override
        public void paint(Graphics g) {
            try {
                imagen = new ImageIcon(getClass().getResource("/icons/fondo_login.png")).getImage();
                g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
                setOpaque(false);
                super.paint(g);
            } catch (Exception e) {
                // Si no se encuentra la imagen, usar fondo sólido
                setBackground(new java.awt.Color(240, 240, 240));
                setOpaque(true);
                super.paint(g);
            }
        }
    }
}
